FROM php:7.4-fpm-alpine

ENV MYSQL_USER=admin \
MYSQL_PASSWORD=password
# Use the default production configuration
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
RUN mkdir -p /home/app

COPY . /home/app

CMD [ "php", "/home/app/index.php" ]