version: "3.1"

services: 
  #the application
  lwhh-app:
    build: .
    ports:
      - 3000:3000
  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: example
  
  adminer:
    image: adminer
    ports: 
     - 8000:8000    
    